export const variables = {
  //cLOUDFLARE
  BUCKET_NAME: process.env.B2_BUCKET_NAME,
  CLOUDFLARE_ACCESS_KEY_ID: process.env.CLOUDFLARE_ACCESS_KEY_ID,
  CLOUDFLARE_SECRET_ACCESS_KEY: process.env.CLOUDFLARE_SECRET_ACCESS_KEY,
  CLOUDFLARE_API_BASE_URL: process.env.CLOUDFLARE_API_BASE_URL,
};
