import { env } from "./envValidation";

export const variables = {
  //CLOUDFLARE
  BUCKET_NAME: env.R2_BUCKET_NAME,
  CLOUDFLARE_ACCESS_KEY_ID: env.CLOUDFLARE_ACCESS_KEY_ID,
  CLOUDFLARE_SECRET_ACCESS_KEY: env.CLOUDFLARE_SECRET_ACCESS_KEY,
  CLOUDFLARE_API_BASE_URL: env.CLOUDFLARE_API_BASE_URL,

  //MONGO DB
  MONGO_USERNAME: env.MONGO_USERNAME,
  MONGO_PASSWORD: env.MONGO_PASSWORD,
  MONGO_DB_NAME: env.MONGO_DB_NAME,

  VERCEL_URL: env.VERCEL_URL,
  NEXT_PUBLIC_SITE_URL: env.NEXT_PUBLIC_SITE_URL,
};
