export const variables = {
  //CLOUDFLARE 
  BUCKET_NAME: process.env.R2_BUCKET_NAME,
  CLOUDFLARE_ACCESS_KEY_ID: process.env.CLOUDFLARE_ACCESS_KEY_ID,
  CLOUDFLARE_SECRET_ACCESS_KEY: process.env.CLOUDFLARE_SECRET_ACCESS_KEY,
  CLOUDFLARE_API_BASE_URL: process.env.CLOUDFLARE_API_BASE_URL,

  //MONGO DB
  MONGO_USERNAME: process.env.MONGO_USERNAME,
  MONGO_PASSWORD: process.env.MONGO_PASSWORD,
  MONGO_DB_NAME: process.env.MONGO_DB_NAME,
};
